config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "psychologists#index"

  resources :psychologists, only: [:index]
  resources :evaluateds do
    collection do
      post :create_questionnaire_sent
      get :show
    end
  end

  resources :evaluation_interaction do
    member do
      get :show
      post :submit
      get :confirmation
      post :check_evaluated
      get :validate
    end
  end
  resources :questionnaires_sent

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/evaluated.rb
class Evaluated < ApplicationRecord
  validates :name, :cpf, :email, :birth_date, presence: true
  validates :email, presence: true, uniqueness: true, format: {
    with: URI::MailTo::EMAIL_REGEXP, message: "formato de email inválido"
  }
  validate :valid_cpf

  include PgSearch::Model
  pg_search_scope :search_by_name_and_cpf,
  against: [ :name, :cpf ],
  using: {
    tsearch: { prefix: true }
  }

  def valid_cpf
    return if cpf.blank?

    errors.add(:cpf, "O CPF não é válido") unless CPF.valid?(cpf)
  end
end

app/models/psychologist.rb
class Psychologist < ApplicationRecord
  belongs_to :user, foreign_key: "users_id"
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
end

app/models/questionnaire_sent.rb
class QuestionnaireSent < ApplicationRecord
  belongs_to :psychologist
  belongs_to :evaluated
  belongs_to :questionnaire
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :psychologist, foreign_key: "users_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/evaluateds_controller.rb
class EvaluatedsController < ApplicationController
  before_action :find_evaluated, only: %i[show edit update]

  def index
    @evaluateds = Evaluated.all
  end

  def show
    @questionnaires_sent = QuestionnaireSent.where(evaluated_id: @evaluated.id)
    @questionnaires = Questionnaire.all
  end

  def create_questionnaire_sent
    psychologist = Psychologist.find_by(users_id: current_user[:id])

    questionnaires_sent = QuestionnaireSent.create!(
      psychologist_id: psychologist.id,
      evaluated_id: params[:evaluated_id],
      questionnaire_id: params[:questionnaire_id],
      status: "Pendente"
    )

    send_mail(questionnaires_sent)
  end

  def send_mail(questionnaires_sent)
    evaluated = Evaluated.find(params[:evaluated_id])
    questionnaire = Questionnaire.find(params[:questionnaire_id])

    QuestionnaireSendMailer.send_questionnaire_link(evaluated, questionnaire, questionnaires_sent).deliver_now

    redirect_to evaluateds_path, notice: 'Email enviado com sucesso!'
  end

  def new
    @evaluated = Evaluated.new
  end

  def create
    @evaluated = Evaluated.new(evaluated_params)
    evaluated_params[:psychologist_id] = current_user.id

    if @evaluated.save
      redirect_to evaluated_path(@evaluated.id),
                  notice: 'Avaliado criado com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @evaluated.update!(evaluated_params)
      redirect_to evaluated_path(@evaluated), notice: "Avaliado atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def evaluated_params
    params.require(:evaluated).permit(:name, :cpf, :email, :birth_date)
  end

  def find_evaluated
    @evaluated = Evaluated.find(params[:id])
  end
end

app/controllers/evaluation_interaction_controller.rb
class EvaluationInteractionController < ApplicationController
  skip_before_action :authenticate_user!

  def validate; end

  def check_evaluated
    @evaluated = Evaluated.find_by(name: params[:name], email: params[:email], cpf: params[:cpf], birth_date: params[:birth_date].to_date)
    url = request.original_url
    updated_url = url.sub('check_evaluated', 'validate')

    if @evaluated
      @questionnaires_sent = QuestionnaireSent.find_by(evaluated_id: @evaluated.id, link_email: updated_url)
      session[:questionnaires_sent] = @questionnaires_sent.attributes

      redirect_to evaluation_interaction_path(id: @questionnaires_sent.questionnaire_id)
    else
      flash[:notice] = 'Dados inválidos, tente novamente.'
      render :validate, status: :unprocessable_entity
    end
  end

  def show
    @questions = Questionnaire.find(params[:id])
  end

  def submit
    @questionnaires_sent = QuestionnaireSent.find(session[:questionnaires_sent]["id"])

    session.delete(:questionnaires_sent)

    @questionnaires_sent.update(answers: params[:responses], status: "Finalizado")

    redirect_to confirmation_evaluation_interaction_path, notice: 'Respostas enviadas com sucesso!'
  end
end

app/controllers/psychologists_controller.rb
class PsychologistsController < ApplicationController
  def index
    @psychologist = Psychologist.find_by(users_id: current_user.id)

    if params[:query] && params[:query].present?
      @evaluateds = Evaluated.search_by_name_and_cpf(params[:query])
    else
      @evaluateds = Evaluated.all.order(name: :asc)
    end
  end
end

app/controllers/questionnaires_sent_controller.rb
class QuestionnairesSentController < ApplicationController
  before_action :find_questionnaires_sent

  def show
    calculate_points unless find_questionnaires_sent.points.positive?
    @questionnaire_sent = find_questionnaires_sent
    @questions = @questionnaire_sent.questionnaire.questions

    @formatted_questions_and_answers = []

    @questionnaire_sent.answers.each do |key, value|
      @questions.each do |question|
        next unless key.downcase == question["pergunta"].parameterize

        @formatted_questions_and_answers << { question: question["pergunta"], answer: value }
      end
    end

    @formatted_questions_and_answers
  end

  private

  def calculate_points
    questionnaire_sent = find_questionnaires_sent
    questions = questionnaire_sent.questionnaire.questions
    questionnaire_sent_answers = questionnaire_sent.answers
    count_points = 0

    questionnaire_sent_answers.each do |answer|
      q = answer[0]
      a = answer[1]
      questions.each do |question|
        next unless q.downcase == question["pergunta"].parameterize

        question["resposta"].each_with_index do |resp, index|
          next unless a == resp

          case index
          when 0
            count_points += 3
          when 1
            count_points += 2
          when 2
            count_points += 1
          when 3
            count_points += 0
          end
        end
      end
    end

    questionnaire_sent.update(points: count_points)
  end

  def find_questionnaires_sent
    QuestionnaireSent.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/evaluateds/_cards.html.erb
<div class="wrap">
  <% @evaluateds.each do |evaluated| %>
    <%= link_to evaluated_path(evaluated), class: "card-link" do %>
      <div class="card">
        <div class="top">
          <h1><%= evaluated.name %></h1>
        </div>
        <div class="bottom">
          <p><span>CPF:</span> <%= CPF::Formatter.format(evaluated.cpf) %></p>
          <p><span>E-mail:</span> <%= evaluated.email %></p>
          <p><span>Data de nascimento:</span> <%= evaluated.birth_date.strftime("%d/%m/%Y") %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/evaluateds/_form.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-center">
    <%= form_with model: @evaluated, local: true, html: {class: "bootstrap-form"} do |form| %>
      <div class="form-information">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name, class: "form-control", required: true %>
      </div>

      <div class="form-information">
        <%= form.label :cpf, "CPF" %>
        <%= form.text_field :cpf, class: "form-control",  pattern: "[0-9]*", required: true %>
        <% if @evaluated.errors[:cpf].any? %>
          <p class="text-danger"><%= @evaluated.errors[:cpf].first %></p>
        <% end %>
      </div>

      <div class="form-information">
        <%= form.label :email, "E-mail" %>
        <%= form.email_field :email, class: "form-control", required: true %>
      </div>

      <div class="form-information">
        <%= form.label :birth_date, "Data de Nascimento" %>
        <%= form.date_field :birth_date, class: "form-control", required: true %>
      </div>

      <div class="form-group mt-3">
        <%= form.submit 'Enviar', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/evaluateds/new.html.erb
<h1>Crie um novo Avaliado</h1>

<%= render 'form', evaluated: @evaluate %>

app/views/evaluateds/show.html.erb
<h1>Detalhes do Avaliado</h1>
<div class="container mt-5 ">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Detalhes do Avaliado</h5>
          <p class="card-text">Nome: <%= @evaluated.name %></p>
          <p class="card-text">CPF: <%= CPF::Formatter.format(@evaluated.cpf) %> </p>
          <p class="card-text">E-mail: <%= @evaluated.email %></p>
          <p class="card-text">Data de nascimento: <%= @evaluated.birth_date.strftime("%d/%m/%Y") %></p>

        </div>
      </div>
    </div>
    <div class="col mt-5">
      <div class="col">
        <!-- Formulário -->
        <%= form_with url: create_questionnaire_sent_evaluateds_path, method: :post, local: true do |form| %>
            <div class="mb-3">
            <label for="questionnaire" class="form-label">Selecione o Questionário</label>
            <%= form.select :questionnaire_id, @questionnaires.collect { |q| [q.title, q.id] }, {}, { class: "form-select", id: "questionnaire" } %>
          </div>
          <%= form.hidden_field :evaluated_id, value: @evaluated.id %>  <!-- Campo oculto para o evaluated_id -->
          <%= form.submit "Enviar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Questionários</h5>
        <% if @questionnaires_sent.blank? %>
          <p class="card-text">Este avaliado ainda não possui nenhum questionário enviado.</p>
        <% else %>
          <div class="row row-cols-1 row-cols-md-2 g-4 mb-5">
            <% @questionnaires_sent.each do |questionnaire_sent| %>
              <div class="col">
                <div class="card h-100">
                  <div class="card-body d-flex justify-content-between align-items-center">
                    <p class="card-text m-0"><%= questionnaire_sent.questionnaire.title %> - Status: <%= questionnaire_sent.status %></p>
                    <% if questionnaire_sent.status == "Finalizado" %>
                      <%= link_to 'Ver respostas e pontuação', questionnaires_sent_path(questionnaire_sent.id), class: "btn btn-primary" %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to 'Voltar', psychologists_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/evaluation_interaction/confirmation.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body text-center">
          <h2 class="card-title">Respostas enviadas com sucesso. Aguarde retorno.</h2>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/evaluation_interaction/show.html.erb
<h1 class="text-center my-5"><%= @questions.title %></h1>

<%= form_with(url: submit_evaluation_interaction_path, method: :post, class: "container") do |f| %>
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <% @questions.questions.each_with_index do |question, index| %>
        <div class="mb-3 text-center">
          <strong><p class="font-weight-bold mt-5"><%= question["pergunta"] %></p></strong>
          <% question["resposta"].each_with_index do |option, idx| %>
            <div class="form-check form-check-inline">
              <%= f.radio_button "responses[#{question['pergunta'].parameterize}]", option, id: "response_#{index + 1}_#{idx}", class: "form-check-input", checked: idx == 3%>
              <%= f.label "response_#{index + 1}_#{idx}", option, class: "form-check-label" %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="mt-4 d-flex justify-content-center">
        <%= f.submit "Enviar Respostas", class: "btn btn-primary mb-5" %>
      </div>
    </div>
  </div>
<% end %>

app/views/evaluation_interaction/validate.html.erb
<h1>Por favor preencha com seus dados</h1>

<div class="container mt-5">
  <div class="d-flex justify-content-center">
    <%= form_with url: check_evaluated_evaluation_interaction_path, method: :post, local: true do |form| %>
      <div class="form-information">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name, class: "form-control", required: true %>
      </div>

      <div class="form-information">
        <%= form.label :cpf, "CPF" %>
        <%= form.text_field :cpf, class: "form-control",  pattern: "[0-9]*", required: true %>
      </div>

      <div class="form-information">
        <%= form.label :email, "E-mail" %>
        <%= form.email_field :email, class: "form-control", required: true %>
      </div>

      <div class="form-information">
        <%= form.label :birth_date, "Data de Nascimento" %>
        <%= form.date_field :birth_date, class: "form-control", required: true %>
      </div>

      <div class="form-group mt-3">
        <%= form.submit 'Validar', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineQuestionnaire</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/psychologists/index.html.erb
<h1>Bem vindo <%= current_user.psychologist.name %></h1>
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: psychologists_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Pesquise por Nome ou CPF"
        %>
      <%= submit_tag "Pesquisar", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= render "evaluateds/cards" %>

app/views/questionnaires_sent/_form.html.erb
<div class="container">
  <%= form_with model: @questionnaires_sent, local: true do |form| %>
    <div class="field">
      <%= form.label :nome %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :cpf %>
      <%= form.text_field :cpf %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="field">
      <%= form.label :data_de_nascimento %>
      <%= form.date_field :birth_date %>
    </div>

    <div class="actions">
      <%= form.submit 'Enviar' %>
    </div>
  <% end %>
</div>

app/views/questionnaires_sent/show.html.erb
<div class="container my-5 py-5 border rounded bg-light">
  <h2 class="text-center mb-5">Detalhes da avaliação: "<%= @questionnaire_sent.questionnaire.title %>" do avaliado: <%= @questionnaire_sent.evaluated.name %></h2>

  <div class="row mb-4">
    <div class="col-12">
      <h3>Psicólogo que solicitou o teste:</h3>
      <p class="lead"><%= @questionnaire_sent.psychologist.name %></p>
    </div>
  </div>

  <div>
    <strong>Respostas:</strong>
    <ul class="list-unstyled">
      <% @formatted_questions_and_answers.each do |params| %>
        <li class="mb-3">
          <strong><%= params[:question] %>:</strong>
          <div><%= params[:answer] %></div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="row">
    <div class="col-12">
      <h2>Pontos:
        <p class="lead"><%= @questionnaire_sent.points %></p>
      </h2>
    </div>
  </div>
</div>
<%= link_to 'Voltar', evaluated_path(@questionnaire_sent.evaluated_id), class: "btn btn-primary" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar">
  <div class="container-fluid">
    <%= link_to "/psychologists#index", class: "navbar-brand" do %>
      <%= image_tag "https://recursos.vetoreditora.com.br/i/logo-white.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="nav-item active">
            <%= link_to "Inicio", "/psychologists#index", class: "nav-link" %>
            <%= link_to "Cadastrar Avaliado", "/evaluateds/new", class: "nav-link" %>
          </div>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Inicio", "/psychologists#index", class: "dropdown-item" %>
          </div>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>